### ISSUE TITLE
Can we change the name of the project into plantlab?

### ISSUE THREAD

**Issue by pradal** [openalea/plantlab#1]
PlantLab is a better name for the project.
oalab is cryptic and oalab-plant is a kind of namespace encrytion.

PlantLab (in lowercase for a directory name) is a nice marketing name.

**Comment by gbaty** [comment]
I agree, will be done soon

**Comment by gbaty** [comment]
done

**Comment by cgodin** [comment]
Bonjour Guillaume et Christophe 

Le nommage des choses à ce niveau très général est un point important qui va rester. Il faut prendre un peu de temps pour peser les choses et j'aimerais qu'on en discute ensemble avant d'arreter ces décisions.
On peut voir ca demain ou Lundi.

A demain

Christophe

**Comment by pradal** [comment]
Sure.

Tomorrow will be hard for me, but Monday is OK.
It is quite easy to refactor later on, but it is critical to have good naming and organisation.
@gbaty will summarize the first layout we have choosed.

Christophe P.
